---
title: "hw4problem2"
author: "HuilanTang_CandaceHaghighi"
date: "10/27/2017"
output: html_document
---
## Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(
  fig.width = 7,
  fig.asp = 1,
  out.width = "110%")
library(janitor)
library(lubridate)
library(readxl)
library(tidyverse)
library(dplyr)
```

## Load and Tidy: Data-Lead
```{r load and tidy the data}
# load and tidy the pols_month dataset
pols_data = read_csv("./fivethirtyeight_datasets/pols-month.csv") %>% 
  clean_names() %>% 
  na.omit() %>% 
  rename(date = mon) %>% 
  mutate(date = floor_date(ymd(date), "month")) %>% 
  mutate(president = recode(prez_gop, `0` = "dem", `1` = "gop", `2` = "gop")) %>%
  select(-prez_dem, -prez_gop)


# load and tidy the  GDP data
GDP_data = read_csv("./fivethirtyeight_datasets/GDP.csv") %>% 
  clean_names() %>% 
  filter(!(value == ".")) %>% 
  mutate(date = as.Date(date))



# combine the two datasets to pols_GDP_data
pols_GDP_data = left_join(pols_data, GDP_data, by = "date")
```

## Creating Plot: Data-Collaborator
```{r, line graph}
pols_GDP_data %>%
  group_by(president) %>%
  ggplot(aes(x = date, y = as.numeric(value),  group = president, color = president))   + 
  geom_point(aes(color = president), alpha = .5) +
  geom_smooth(se = FALSE) +
    labs(title = "GDP Value Over Time", x = "Date", y = "GDP Value") +
    theme(plot.title = element_text(hjust = 0.5), axis.ticks.y = element_blank())
```

#### According to the 'GDP Value Over Time' line graph, Democratic presidents appear to be generally associated with higher GDP when compared to Republican presidents. However, this trend appears to have been reversed beginning around 2001.
